//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace List_Controls {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class цф {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal цф() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("List_Controls.цф", typeof(цф).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Earth is the third planet in the Solar System by distance from the Sun. It is the densest, fifth in diameter and mass among all the 
        ///planets in the Solar System and the largest among the terrestrial planets, which also include Mercury, Venus and Mars. The only 
        ///body in the Universe currently known to man that is inhabited by living organisms. 
        ///
        ///Scientific evidence indicates that the Earth formed from a solar nebula about 4.54 billion years ago 
        ///Go to section &quot;#History of the Earth&quot; and soon after that  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextEarth {
            get {
                return ResourceManager.GetString("TextEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Jupiter is the largest planet in the Solar System, the fifth in distance from the Sun. Along with Saturn, Jupiter is classified as a gas giant.
        ///The planet has been known to people since ancient times, which is reflected in the mythology and religious beliefs of various cultures: Mesopotamian, Babylonian, Greek and others. The modern name of Jupiter comes from the name of the ancient Roman supreme god of thunder.
        ///
        ///A number of atmospheric phenomena on Jupiter: storms, lightning, aurorae, have a scale that  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextJupiter {
            get {
                return ResourceManager.GetString("TextJupiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone: 8(546)777-54-43-23
        ///
        ///Email: (hidden)
        ///
        ///Works 24-7 for you.
        ///
        ///Latest news about space only with us!
        ///.
        /// </summary>
        public static string TextKontakt {
            get {
                return ResourceManager.GetString("TextKontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Here are the best materials on space!
        ///
        ///The information is verified and updated every day, thanks to joint efforts!
        ///
        ///At the moment, our professionals are translating the site into different languages, so at the moment not everything is translated.
        ///
        ///We will fix this soon!!.
        /// </summary>
        public static string TextMain {
            get {
                return ResourceManager.GetString("TextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mars is the fourth planet from the Sun and the seventh largest in the Solar System; its mass is 10.7% of the Earth&apos;s mass. Go to the section &quot;#Basic information&quot; It is named after Mars, the ancient Roman god of war, corresponding to the ancient Greek Ares. Go to the section &quot;#In ancient mythology&quot; Mars is also called the &quot;red planet&quot; because of the reddish tint of its surface, given to it by the mineral maghemite - γ-iron(III) oxide. 
        ///Mars is a terrestrial planet with a thin atmosphere (the surface pressur [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextMars {
            get {
                return ResourceManager.GetString("TextMars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mercury is the smallest planet in the Solar System and the closest to the Sun. It is named after the Roman god of commerce, Swift Mercury, because it moves across the sky faster than the other planets. Its period of revolution around the Sun is only 87.97 Earth days - the shortest of all the planets in the Solar System. 
        ///&lt;LineBreak/&gt; 
        ///Mercury&apos;s apparent distance from the Sun, as seen from Earth, never exceeds 28°. This proximity to the Sun means that the planet can only be seen for a short time after suns [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextMercury {
            get {
                return ResourceManager.GetString("TextMercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Neptune is the eighth and farthest planet from the Sun in the Solar System. Its mass is 17.2 times that of Earth and it is the third largest planet in the Solar System, and Neptune has the fourth largest equatorial diameter, 3.9 times larger than Earth. The planet is named after Neptune, the Roman god of the seas.
        ///
        ///Discovered on September 23, 1846, Neptune became the first planet discovered using mathematical calculations.
        ///The discovery of unpredictable changes in Uranus&apos; orbit gave rise to the hypothesi [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextNeptune {
            get {
                return ResourceManager.GetString("TextNeptune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Planet Nine is a hypothetical planet in the outer Solar System whose gravitational attraction could explain the average anomaly in the distribution of orbits of isolated trans-Neptunian objects (TNOs), found mostly outside the Kuiper belt in the scattered disk. An undiscovered mini-Neptune-sized planet would have a mass of 5-10M⊕, a diameter two to four times that of Earth, and an elongated orbit with an orbital period of approximately 15,000 Earth years. To date, searches for Planet Nine have been unsucces [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextNinePlanet {
            get {
                return ResourceManager.GetString("TextNinePlanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saturn is the sixth planet from the Sun and the second largest planet in the Solar System after Jupiter.
        ///Saturn is classified as a gas giant planet. Saturn is named after the Roman god of agriculture. Go to 
        ///section &quot;#Saturn in Culture&quot; Saturn&apos;s symbol is ♄.
        ///
        ///Saturn is mostly composed of hydrogen, with traces of helium and water, methane, ammonia and heavier elements.
        ///The inner region is a relatively small core of iron, nickel and ice, covered by a thin layer of metallic hydrogen and a gaseous outer la [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextSaturn {
            get {
                return ResourceManager.GetString("TextSaturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Solar System is a planetary system that includes the central star, the Sun, and all natural celestial bodies in 
        ///heliocentric orbits. It formed by the gravitational compression of a cloud of gas and dust approximately 4.57 billion years ago. 
        ///
        ///The four planets closest to the Sun, called the terrestrial planets — Mercury, Venus, Earth, and Mars — are composed
        ///primarily of silicates and metals. The four planets farther from the Sun — Jupiter, Saturn, Uranus, and Neptune 
        ///(also called the gas giants)  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextSolarSystem {
            get {
                return ResourceManager.GetString("TextSolarSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The central object of the Solar System is the Sun, a main sequence star of spectral class G2V, a yellow dwarf. 
        ///The Sun contains the overwhelming majority of the total mass of the system (about 99.866%), it holds the planets and other bodies belonging to the Solar System with its 
        ///gravity. The four largest objects, the gas giants, make up 99% of the remaining mass (with Jupiter and Saturn accounting for the largest part, about 90%). 
        ///
        ///Most large objects orbiting the Sun move in almost the same plane, ca [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextStruct {
            get {
                return ResourceManager.GetString("TextStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Sun is the star of the Solar System and its main component. Its mass (332,900 Earth masses) is large enough to support 
        ///thermonuclear reactions in its interior, releasing large amounts of energy that are radiated into space, mainly 
        ///as electromagnetic radiation, with a maximum in the 400–700 nm wavelength range, corresponding to visible light. 
        ///&lt;LineBreak/&gt; 
        ///According to stellar classification, the Sun is a typical yellow dwarf of class G2. This name can be misleading, since compared 
        ///to most stars [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextSun {
            get {
                return ResourceManager.GetString("TextSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uranus is a planet in the Solar System, the seventh farthest from the Sun, the third largest in diameter, and the fourth most massive. 
        ///It was discovered in 1781 by the English astronomer William Herschel and named after the Greek god of the sky, Uranus. 
        ///
        /// Uranus was the first planet discovered in modern times and with the help of a telescope. It was discovered by William Herschel on March 13, 1781, thus expanding the boundaries of the Solar System in the eyes of man for the first time since antiquity.  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextUranus {
            get {
                return ResourceManager.GetString("TextUranus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Venus is the second planet from the Sun and the sixth largest in the Solar System, along with Mercury, Earth and Mars
        ///and belongs to the family of terrestrial planets. It is named after the ancient Roman goddess of love, Venus. According to a number of characteristics, such as its mass and size, Venus is considered the &quot;sister&quot; of the Earth. The Venusian year is 224.7 Earth days. It has the longest period of rotation around its axis (about 243 Earth days, an average of 243.0212 ± 0.00006 days) of all the p [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextVenus {
            get {
                return ResourceManager.GetString("TextVenus", resourceCulture);
            }
        }
    }
}
