//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace List_Controls {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsUI() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("List_Controls.StringsUI", typeof(StringsUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля.
        /// </summary>
        public static string TabEarth {
            get {
                return ResourceManager.GetString("TabEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Юпитер.
        /// </summary>
        public static string TabJupiter {
            get {
                return ResourceManager.GetString("TabJupiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string TabKontakt {
            get {
                return ResourceManager.GetString("TabKontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная.
        /// </summary>
        public static string TabMain {
            get {
                return ResourceManager.GetString("TabMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Марс.
        /// </summary>
        public static string TabMars {
            get {
                return ResourceManager.GetString("TabMars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меркурий.
        /// </summary>
        public static string TabMercury {
            get {
                return ResourceManager.GetString("TabMercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нептун.
        /// </summary>
        public static string TabNeptun {
            get {
                return ResourceManager.GetString("TabNeptun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Девятая планета.
        /// </summary>
        public static string TabNinePlanet {
            get {
                return ResourceManager.GetString("TabNinePlanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сатурн.
        /// </summary>
        public static string TabSaturn {
            get {
                return ResourceManager.GetString("TabSaturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Солнечная система.
        /// </summary>
        public static string TabSolarSystem {
            get {
                return ResourceManager.GetString("TabSolarSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Структура.
        /// </summary>
        public static string TabStruck {
            get {
                return ResourceManager.GetString("TabStruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Солнце.
        /// </summary>
        public static string TabSun {
            get {
                return ResourceManager.GetString("TabSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уран.
        /// </summary>
        public static string TabUran {
            get {
                return ResourceManager.GetString("TabUran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Винера.
        /// </summary>
        public static string TabVenus {
            get {
                return ResourceManager.GetString("TabVenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля́ — третья по удалённости от Солнца планета Солнечной системы. Самая плотная, пятая по диаметру и массе среди всехпланет Солнечной системы и крупнейшая среди планет земной группы, в которую входят также Меркурий, Венера и Марс. Единственное
        ///известное человеку в настоящее время тело во Вселенной, населённое живыми организмами.
        ///Научные данные указывают на то, что Земля образовалась из солнечной туманности около 4,54 миллиарда лет назадПерейти к разделу
        ///«#История Земли» и вскоре после этого обрела свой [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextEarth {
            get {
                return ResourceManager.GetString("TextEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Юпи́тер — крупнейшая планета Солнечной системы, пятая по удалённости от Солнца. Наряду с Сатурном, Юпитер классифицируется
        ///как газовый гигант.
        ///Планета была известна людям с глубокой древности, что нашло своё отражение в мифологии и религиозных верованиях различных
        ///культур: месопотамской, вавилонской, греческой и других. Современное название Юпитера происходит от имени древнеримского 
        ///верховного бога-громовержца.
        /// Ряд атмосферных явлений на Юпитере: штормы, молнии,сияния, — имеет масштабы, на порядки пр [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextJupiter {
            get {
                return ResourceManager.GetString("TextJupiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон: 8(546)777-54-43-23
        ///
        ///Email: top-camp@kosmos.ru
        ///
        ///Работает 24-7 для вас.
        ///
        ///Свежие новости о космосе только у нас!
        ///.
        /// </summary>
        public static string TextKontakt {
            get {
                return ResourceManager.GetString("TextKontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здесь собраны лучшие материалы по космосу!
        ///
        /// Информация проверена и каждый день обновлется, благадоря общими усилиями!
        /// 
        /// На данный момент наши профессионалы переводят сайт на разные языки поэтому в данный момент не все переведенно.
        ///
        /// В скором времени мы это исправим!!.
        /// </summary>
        public static string TextMain {
            get {
                return ResourceManager.GetString("TextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Марс — четвёртая по удалённости от Солнца и седьмая по размеру планета Солнечной системы; масса планеты составляет 10,7 %массы Земли.Перейти к разделу «#Основные сведения» Названа в честь Марса — древнеримского бога войны, соответствующегодревнегреческому Аресу.Перейти к разделу «#В античной мифологии» Также Марс называют «красной планетой» из-за красноватого оттенка поверхности, придаваемого ей минералом маггемитом — γ-оксидом железа(III).Марс — планета земной группы с разреженной атмосферой (давление на п [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextMars {
            get {
                return ResourceManager.GetString("TextMars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мерку́рий — наименьшая планета Солнечной системы и самая близкая к Солнцу. Названа вчесть древнеримского бога торговли — быстрого Меркурия, поскольку она движется по небу быстрее других планет. Её период обращения вокруг Солнца составляет всего 87,97 земных суток —  самый короткий среди всех планет Солнечной системы.
        ///  Видимое расстояние Меркурия от Солнца, если смотреть с Земли, никогда не превышает 28°. Эта близость к Солнцу означает, что планету можно увидеть только в течение небольшого времени после за [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextMercury {
            get {
                return ResourceManager.GetString("TextMercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Непту́н — восьмая и самая дальняя от Солнца планета Солнечной системы. Его масса превышает массу Земли в 17,2  раза и является третьей среди планет Солнечной системы, а по экваториальному диаметру Нептун занимает четвёртоеместо, превосходя Землю в 3,9 раза. Планета названа в честь Нептуна — римского бога морей.
        ///   Обнаруженный 23 сентября 1846 года Нептун стал первой планетой, открытой благодаря математическим расчётам.
        ///  Обнаружение непредсказуемых изменений орбиты Урана породило гипотезу о неизвестной п [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextNeptune {
            get {
                return ResourceManager.GetString("TextNeptune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Девятая планета — гипотетическая планета во внешней области Солнечной системы, гравитационное притяжение которой может объяснить среднюю аномалию в распределении орбит обособленных транснептуновых объектов (ТНО), обнаруженных в основном за пределами пояса Койпера в рассеянном диске. Неоткрытая планета размером с мининептун должна иметь массу 5-10M⊕, диаметр в два—четыре раза больше земного и вытянутую орбиту с периодом обращения приблизительно 15 тысяч земных лет. На сегодняшний день поиски Девятой планеты  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextNinePlanet {
            get {
                return ResourceManager.GetString("TextNinePlanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сату́рн — шестая планета по удалённости от Солнца и вторая по размерам планета в Солнечной системе после Юпитера.Сатурн классифицируется как газовая планета-гигант. Сатурн назван в честь римского бога земледелия.Перейти к  разделу «#Сатурн в культуре» Символ Сатурна — ♄.
        ///  В основном Сатурн состоит из водорода, с примесями гелия и следами воды, метана, аммиака и тяжёлых элементов.Внутренняя область представляет собой относительно небольшое ядро из железа, никеля и льда, покрытое тонким слоемметаллического  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextSaturn {
            get {
                return ResourceManager.GetString("TextSaturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Со́лнечная систе́ма — планетная система, включающая в себя центральную звезду Солнце и все естественные космические объекты не гелиоцентрических орбитах.
        ///Она сформировалась путём гравитационного сжатия газопылевого облака примерно 4,57 млрд лет назад.
        ///  Четыре ближайшие к Солнцу планеты, называемые планетами земной группы, — Меркурий, Венера, Земля и Марс — состоят в  основном из силикатов и металлов. Четыре более удалённые от Солнца планеты — Юпитер, Сатурн, Уран и Нептун также называемые газовыми гигант [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextSolarSystem {
            get {
                return ResourceManager.GetString("TextSolarSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Центральным объектом Солнечной системы является Солнце — звезда главной последовательности спектрального класса G2V, жёлтый карлик.   В Солнце сосредоточена подавляющая часть всей массы системы (около 99,866 %), оно удерживает своим  тяготением планеты и прочие тела, принадлежащие к Солнечной системе. Четыре крупнейших объекта —  газовые гиганты — составляют 99 % оставшейся массы (при этом большая часть приходится на Юпитер и Сатурн — около 90 %).
        ///Большинство крупных объектов, обращающихся вокруг Солнца, д [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextStruct {
            get {
                return ResourceManager.GetString("TextStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Солнце — звезда Солнечной системы и её главный компонент. Его масса (332 900 масс Земли) достаточно велика для поддержания термоядерной реакции в его недрах, при которой высвобождается большое количество энергии, излучаемой в пространство в основномв виде электромагнитного излучения, максимум которого приходится на диапазон длин волн 400—700 нм, соответствующий видимому свету.
        ///По звёздной классификации Солнце — типичный жёлтый карлик класса G2. Это название может ввести в заблуждение, так как по сравнению  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextSun {
            get {
                return ResourceManager.GetString("TextSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ура́н — планета Солнечной системы, седьмая по удалённости от Солнца, третья по диаметру и четвёртая по массе.  Была открыта в 1781 году английским астрономом Уильямом Гершелем и названа в честь греческого бога неба Урана.
        ///  Уран стал первой планетой, обнаруженной в Новое время и при помощи телескопа. Его открыл Уильям Гершель 13 марта 1781 года, тем самым впервые со времён античности расширив границы Солнечной системы в глазах человека. Несмотря на то, что порой Уран различим невооружённым глазом, более ра [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextUranus {
            get {
                return ResourceManager.GetString("TextUranus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вене́ра — вторая по удалённости от Солнца и шестая по размеру планета Солнечной системы, наряду с Меркурием, Землёй и Марсом
        ///принадлежащая к семейству планет земной группы. Названа в честь древнеримской богини любви Венеры. По ряду характеристик —например, по массе и размерам — Венера считается «сестрой» Земли. Венерианский год составляет 224,7 земных суток. Она имеет
        ///самый длинный период вращения вокруг своей оси (около 243 земных суток, в среднем 243,0212 ± 0,00006 сут) среди всех планет
        ///Солнечной сист [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextVenus {
            get {
                return ResourceManager.GetString("TextVenus", resourceCulture);
            }
        }
    }
}
